### ISSUE TITLE
Recommend building with runTests.sh

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#249]
A discussion in Slack #typo3-documentation revealed that active Core contributors/testers suggest "building" TYPO3 (composer+yarn/grunt) with the `runTests.sh` command located in the Core repository.

`Build/Scripts/runTests.sh -s composerInstall`
`Build/Scripts/runTests.sh -s buildCss`
`Build/Scripts/runTests.sh -s buildJavascript` 

This requires docker/docker-compose for which we already have a short section here: https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Testing/Index.html#prerequisites

We could improve positive guidance by the manual to put that as "recommended".
In fact a lot of confusing information can then be streamlined:

yarn:
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Setup/SetupTypo3.html#yarn-build
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Appendix/OSX/InstallNpm.html
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Appendix/OSX/InstallGrunt.html

composer:
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Setup/Prerequisites.html#composer
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Setup/SetupTypo3.html#composer-install
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Appendix/OSX/InstallComposer.html
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Appendix/SettingUpTypo3Ddev.html#install-dependencies-via-composer

"grunt" should not be under Prerequisites:
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Setup/Prerequisites.html#grunt 

We could keep the other options (host-installed `yarn`/`composer`, `ddev exec yarn` etc.) for "advanced" users - which might not even be necessary.

**Comment by sypets** [comment]
I agree. We should also update several places, e.g. cleanup command:

see Slack: (by Stefan Bürk)
`git reset --hard origin/main && git pull --rebase ; Build/Scripts/runTests.sh -s clean ; Build/Scripts/runTests.sh -s composerInstall`

https://typo3.slack.com/archives/C03AM9R17/p1651003255888809

* I removed the phpstan because that is not relevant for the cleanup

--------------

If some things can be streamlined / removed - all for it. In particular - if pages not TYPO3 specific - information maybe best referred to elsewhere.

This page is currently empty, not sure why: https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Appendix/OSX/InstallComposer.html

**Comment by jonaseberle** [comment]
I can promise to work on it but can't promise it quickly.
