### ISSUE TITLE
Add an Example bug report with steps to reproduce and links to resourses

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#48]
There are various resources and examples for templates in projects. 

Following could be included:

- system environment (browser, TYPO3 version ...)
- steps to reproduce
- expected behaviour / current behaviour
- logs / stacktrace
- screenshot / video

**Comment by erredeco** [comment]
I sometimes find myself comfortable with this kind of "structure" when I write a bug report:

h2. Prerequisites
- here you should add as much details as possible about your TYPO3 configuration, so people can try 
to reproduce your problem with your exact settings. 
For example, you can add your TypoScript configuration (only the parts relevant to the issue) or if you are using a multilanguage configuration (if your issue is about language handling, that is).
Also, add here details about your environment (TYPO3 version, PHP version, MySQL version)

h2. Steps to reproduce
- this is crucial. be precise and write every step that you feel is important to get the same issue you had. Do repeat yourself if necessary (we won't judge your literary skills)

h2. Expected results
- add here what results did you expect to come out of your configuration

h2. Current results
- add here instead what is the result; this is the description of the issue you are facing

**Comment by sypets** [comment]
This is done.
